name: craftcms
type: php
docroot: web
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
bind_all_interfaces: true
host_webserver_port: "8888"
host_db_port: "3307"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
default_container_timeout: "240"
