name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    uses: Box-of-Dragons/StructuredChaos/.github/workflows/family-deploy.yml@master
    with:
      branch: master
      environment: production
    secrets: inherit
